### ISSUE TITLE
Crash on 2.0.1

### ISSUE THREAD

**Issue by thehappydinoa** [ConorTheDev/LockWidgets#14]
Hi, I am on iOS 13.3.1 on my iPhone Pro Max and my device crashes to safe mode after updating to 2.0.1 my device boots to the launch screen before crashing just as the LockWidget starts to show.

**Comment by thehappydinoa** [comment]
Weird, I used Cr4shed to determine that the issue comes from ColorNotifs. Is there some conflict with that tweak and this one?

**Comment by conorthedev** [comment]
Yeah, there could be. Disable the tweak in iCleaner and see if LockWidgets works, if it does contact the developer of that tweak.

**Comment by thehappydinoa** [comment]
Ya turns out it was something weird with `Lynx` and `ColorfulNotifs`.
