### ISSUE TITLE
Widget selection does not work properly

### ISSUE THREAD

**Issue by paxter** [ConorTheDev/LockWidgets#4]
First of all: Great tweak! I was looking for something like this since days, because I want my calendar entries on the lockscreen without swiping.

I'm on iOS 12.4.3 and installed the tweak from the dynastic repo. The tweak is successfully installed but if I'm trying to select some widgets, the selector jumps around and randomly (de)select any widgets.

**Comment by conorthedev** [comment]
This was identified a while ago and will be fixed in the next public update

**Comment by paxter** [comment]
Awesome. Thank you. :)
