### ISSUE TITLE
1.1 instantly crashes springboard

### ISSUE THREAD

**Issue by paxter** [ConorTheDev/LockWidgets#5]
I just upgraded to 1.1 and now the springboard crashes every time (iOS 12.4.3). I had to disable the tweak. :/

**Comment by conorthedev** [comment]
I’m working on this as we speak

**Comment by paxter** [comment]
We never spoke about that, but thanks anyway. :)

**Comment by paxter** [comment]
Oh, that was an idiom. Sorry, my english is to bad. :D
