### ISSUE TITLE
Widgets below not possible anymore?

### ISSUE THREAD

**Issue by paxter** [ConorTheDev/LockWidgets#6]
Will this feature be added again? I don't like swipping to scroll through my widgets.

**Comment by conorthedev** [comment]
I’ll be adding a vertical scroll option in v1.2. It’ll have the option to display 2 widgets at a time. Hope this solves your issue. Will close when implemented

**Comment by paxter** [comment]
Sounds great. Thanks for your hard work to keep this tweak improved!

**Comment by conorthedev** [comment]
Feature was added in f3e8d99e162620dbdcd4fed511a6bf399d468ac1 and merged to ``master`` in #7. Closing issue!
