### ISSUE TITLE
Add option to display widgets without a scrolling view

### ISSUE THREAD

**Issue by paxter** [ConorTheDev/LockWidgets#8]
Thanks for the update, but the vertical scroll option does not work for me. If selected, the horizontal view is still shown. I'm still on iOS 12.4.3.

Thanks and happy holidays!

**Comment by conorthedev** [comment]
Have you tried respring your device?

**Comment by paxter** [comment]
Yes.

**Comment by conorthedev** [comment]
Can you send a screenshot of your LockWidgets settings?

**Comment by paxter** [comment]
![IMG_4499](https://user-images.githubusercontent.com/5040710/71371534-c99a6780-25b1-11ea-8574-fe64958c719c.jpg)

Of course.

**Comment by conorthedev** [comment]
Can you disable the scroll indicator, then respring and then try to scroll down through the widget list?

**Comment by paxter** [comment]
Oh, I got it. It's working but that feature is very confusing. I thought the vertical option brings the view back you implemented on your first version where you can see all widgets without any scrolling. If I have to scroll through my selected widgets, I could just use the default "swipe to right" option on my lock screen and do not need this tweak.

I was looking for an easy possibility to bring the widgets to my lock screen without any changes. Maybe you could implement an option to bring that feature back?

**Comment by conorthedev** [comment]
Yes I can implement a feature to show all widgets with no scrolling.

**Comment by paxter** [comment]
That would be awesome! Thanks a lot for your fast help and replies.
